/** @file
 *
 * @brief ctgrind harness for the constant-time lattice reduction package.
 *
 * THE POISONING MODEL, which mirrors the package's own contract:
 *   - ibz_t VALUES (the limbs) are SECRET.
 *   - ibz_t BITLENS are PUBLIC, and so are shift amounts and loop bounds derived from them.
 *   - the prime p (alg->p) and the precomputed isqrt(p) are PUBLIC.
 * Inputs are generated by the ordinary non-CT quaternion code, so everything is declassified after
 * generation and only the limbs of the actual reduction inputs are re-poisoned.
 */

#include "quaternion_tests.h"
#include <lll.h>
#include <rng.h>
#include <ct_testing.h>
#include <bench_test_arguments.h>
#include <quaternion_data.h>
#include <torsion_constants.h>
#include <encoded_sizes.h>
#include <stdlib.h>
#include <string.h>

#if defined(ENABLE_CT_TESTING)
#include <valgrind/valgrind.h>
#define CTG_CHECK_BEGIN() VALGRIND_ENABLE_ERROR_REPORTING
#define CTG_CHECK_END() VALGRIND_DISABLE_ERROR_REPORTING
#else
#define CTG_CHECK_BEGIN() ((void)0)
#define CTG_CHECK_END() ((void)0)
#endif

#define CTG_ITEMS 2

// --- poison / declassify helpers

// SECRET: the value. Never the bitlen -- see the poisoning model above.
static void
ctg_secret_ibz(ibz_t *x)
{
    CT_TESTING_MAKE_SECRET(x->limbs, sizeof(x->limbs));
}

static void
ctg_public_ibz(ibz_t *x)
{
    CT_TESTING_MAKE_PUBLIC(x, sizeof(*x));
}

static void
ctg_secret_lattice(quat_lattice_t *lat)
{
    ctg_secret_ibz(&lat->denom);
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            ctg_secret_ibz(&lat->basis.m[i][j]);
}

static void
ctg_public_lattice(quat_lattice_t *lat)
{
    ctg_public_ibz(&lat->denom);
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            ctg_public_ibz(&lat->basis.m[i][j]);
}

static void
ctg_secret_ideal(quat_ideal_t *id)
{
    ctg_secret_ibz(&id->x);
    ctg_secret_ibz(&id->y);
    // norm's VALUE is secret; its bitlen is the public `bound` the wrapper reads via
    // ibz_get_bound, so it stays defined.
    ctg_secret_ibz(&id->norm);
}

static void
ctg_public_ideal(quat_ideal_t *id)
{
    ctg_public_ibz(&id->x);
    ctg_public_ibz(&id->y);
    ctg_public_ibz(&id->norm);
}

// --- stage A: quat_lll_reduce_O0_ideal alone, HNF built and declassified first, so a report here
// is in gaussian_xgcd.c / lehmer_xgcd.c / mp.c and nowhere else.
static void
ctg_stage_reduce_O0_ideal(quat_ideal_t *ideals, const quat_alg_t *alg)
{
    quat_lattice_t hnf, reduced;
    quat_lattice_init(&hnf);
    quat_lattice_init(&reduced);

    for (int i = 0; i < CTG_ITEMS; i++) {
        int bound = ibz_get_bound(&(ideals[i].norm)) + 2;
        quat_to_lattice(&hnf, &(ideals[i])); // non-CT setup, run before poisoning
        ctg_public_lattice(&hnf);
        ctg_secret_lattice(&hnf);
        CTG_CHECK_BEGIN();
        quat_lll_reduce_O0_ideal(&reduced, &hnf, alg, bound);
        CTG_CHECK_END();
        ctg_public_lattice(&reduced);
    }
}

// --- stage B: quat_ideal_reduce_basis, what keygen and sign actually call. Over stage A this adds
// quat_to_lattice and the output-bound loops, where a wrapper-level leak would sit.
static void
ctg_stage_reduce_basis(quat_ideal_t *ideals)
{
    quat_lattice_t reduced;
    quat_lattice_init(&reduced);

    for (int i = 0; i < CTG_ITEMS; i++) {
        ctg_public_ideal(&(ideals[i]));
        ctg_secret_ideal(&(ideals[i]));
        CTG_CHECK_BEGIN();
        quat_ideal_reduce_basis(&reduced, &(ideals[i]));
        CTG_CHECK_END();
        ctg_public_lattice(&reduced);
        ctg_public_ideal(&(ideals[i]));
    }
}

// --- stage C1: quat_lll_dual_reduce_ideal alone, so its verdict is separate from the non-CT
// post-processing its wrapper does afterwards (stage C2).
static void
ctg_stage_dual_reduce(quat_lattice_t *lats, const quat_alg_t *alg)
{
    quat_lattice_t reduced;
    ibz_mat_4x4_t Ainv;
    ibz_t gram_diag[4];
    quat_lattice_init(&reduced);
    ibz_mat_4x4_init(&Ainv);
    for (int i = 0; i < 4; i++)
        ibz_init(&gram_diag[i]);

    for (int i = 0; i < CTG_ITEMS; i++) {
        ctg_public_lattice(&(lats[i]));
        ctg_secret_lattice(&(lats[i]));
        CTG_CHECK_BEGIN();
        quat_lll_dual_reduce_ideal(&reduced, gram_diag, &Ainv, &(lats[i]), alg);
        CTG_CHECK_END();
        ctg_public_lattice(&reduced);
        for (int k = 0; k < 4; k++) {
            ctg_public_ibz(&gram_diag[k]);
            for (int j = 0; j < 4; j++)
                ctg_public_ibz(&Ainv.m[k][j]);
        }
        ctg_public_lattice(&(lats[i]));
    }
}

// --- stage C2: quat_lattice_bound_parallelogram -> quat_lll_dual_reduce_ideal, the SIGN path.
// Radius as sign.c produces it, reproduced exactly as lll_ct_benchmarks.c does.
static int
ctg_stage_parallelogram(quat_lattice_t *lats)
{
    int trivial = 0;
    ibz_vec_4_t box;
    ibz_mat_4x4_t U;
    ibz_t rad;
    ibz_vec_4_init(&box);
    ibz_mat_4x4_init(&U);
    ibz_init(&rad);

    ibz_mul_2exp(&rad, &ibz_const_one, RESPONSE_BITS);
    ibz_sub(&rad, &rad, &ibz_const_one);
    ibz_set_bound(&rad, RESPONSE_BITS + 1);
    ibz_mul_2exp(&rad, &rad, 1);

    for (int i = 0; i < CTG_ITEMS; i++) {
        ctg_public_lattice(&(lats[i]));
        ctg_secret_lattice(&(lats[i]));
        CTG_CHECK_BEGIN();
        trivial += !quat_lattice_bound_parallelogram(&box, &U, &(lats[i]), &rad);
        CTG_CHECK_END();
        for (int k = 0; k < 4; k++) {
            ctg_public_ibz(&box.v[k]);
            for (int j = 0; j < 4; j++)
                ctg_public_ibz(&U.m[k][j]);
        }
        ctg_public_lattice(&(lats[i]));
    }

    return trivial;
}

// --- driver

static int
ctg_run(void)
{
    int randret = 0, trivial = 0;
    int pbits = ibz_bitsize(&QUATALG_PINFTY.p);
    // Same two norm scales the three production callers of quat_ideal_reduce_basis see, and the
    // same product-lattice size the signing path produces. Kept in step with lll_ct_benchmarks.c.
    int sec_bits = ibz_bitsize(&SEC_DEGREE);
    int resp_bits = pbits / 2 + 15;
    int prod_bits = 2 * resp_bits;
    quat_alg_t alg;
    quat_ideal_t *ideals;
    quat_lattice_t *lats;

    quat_alg_init_set(&alg, &QUATALG_PINFTY.p);
    ideals = calloc(CTG_ITEMS, sizeof(quat_ideal_t));
    lats = calloc(CTG_ITEMS, sizeof(quat_lattice_t));
    if (!ideals || !lats)
        abort();
    for (int i = 0; i < CTG_ITEMS; i++) {
        quat_ideal_init(&(ideals[i]));
        quat_lattice_init(&(lats[i]));
    }

    printf("CT lattice reduction ctgrind harness: %d-bit prime, %d items per stage\n", pbits, CTG_ITEMS);

    randret = quat_test_input_random_ideal_generation(ideals, sec_bits, CTG_ITEMS);
    if (randret)
        goto fin;
    printf("  stage A  quat_lll_reduce_O0_ideal      %d-bit norms\n", sec_bits);
    ctg_stage_reduce_O0_ideal(ideals, &alg);
    printf("  stage B  quat_ideal_reduce_basis       %d-bit norms\n", sec_bits);
    ctg_stage_reduce_basis(ideals);

    randret = quat_test_input_random_ideal_generation(ideals, resp_bits, CTG_ITEMS);
    if (randret)
        goto fin;
    printf("  stage B  quat_ideal_reduce_basis       %d-bit norms\n", resp_bits);
    ctg_stage_reduce_basis(ideals);

    randret = quat_test_input_resplike_lattice_generation(lats, NULL, prod_bits, CTG_ITEMS);
    if (randret)
        goto fin;
    printf("  stage C1 quat_lll_dual_reduce_ideal     %d-bit lat\n", prod_bits);
    ctg_stage_dual_reduce(lats, &alg);
    printf("  stage C2 quat_lattice_bound_parallelogram  %d-bit lat\n", prod_bits);
    trivial = ctg_stage_parallelogram(lats);
    if (trivial)
        printf("    warning: %d of %d boxes were trivial\n", trivial, CTG_ITEMS);

fin:;
    if (randret)
        printf("Randomness failure in ctg_run\n");
    free(ideals);
    free(lats);
    return randret;
}

int
main(int argc, char *argv[])
{
    uint32_t seed[12] = { 0 };
    int seed_set = 0;

#ifndef ENABLE_CT_TESTING
    fprintf(stderr,
            "\x1b[31mBuilt without ENABLE_CT_TESTING: the poisoning annotations are no-ops and this\n"
            "run checks nothing. See README, 'Constant-time tests'.\x1b[0m\n");
#endif

    for (int i = 1; i < argc; i++) {
        if (!seed_set && !parse_seed(argv[i], seed)) {
            seed_set = 1;
            continue;
        }
        if (strcmp(argv[i], "--help") == 0) {
            printf("Usage: %s [--seed=<seed>]\n", argv[0]);
            printf("Run under valgrind WITHOUT test/ct-quaternion.supp; see this file's header.\n");
            return 1;
        }
    }

    if (!seed_set)
        randombytes_select((unsigned char *)seed, sizeof(seed));

    print_seed(seed);

#if defined(TARGET_BIG_ENDIAN)
    for (int i = 0; i < 12; i++)
        seed[i] = BSWAP32(seed[i]);
#endif

    // init_test_rng, not randombytes_init: the input generators draw through PRNG_default_domain.
    if (init_test_rng(seed) != 0)
        return 1;

    CTG_CHECK_END(); // mute everything; each stage unmutes only across its entry point

    if (ctg_run()) {
        printf("CT lattice ctgrind harness: SETUP FAILURE\n");
        return 1;
    }
    printf("CT lattice ctgrind harness: completed (findings, if any, are valgrind's)\n");
    return 0;
}
