#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
add_parameter_set.py — scaffold a new SQIsign parameter set (variant).

It automates the mechanical, error-prone parts of adding a level:

  * precomp/ref/<name>/       sqisign_parameters.txt, CMakeLists, include/ dir,
                              stub generated .c files (so cmake can configure);
                              the headers there come from `make precomp`
  * gf/ref/<name>/            reference field arithmetic fp_<tag>.c + fp_<tag>_{32,64}.inc
                              (generated with modarith `monty.py` + a generic
                              SQIsign fp_* / encode-decode appendix), CMakeLists
  * nistapi/<name>/           api.c (copied), api.h is generated by precomp
  * ec|hd|id2iso|signature|verification/ref/<name>/  one-line CMake stubs
  * top-level CMakeLists.txt  registers <name> in SVARIANT_S *for ref/opt only*
                              so broadwell/arm64 (which have no asm for it) do
                              not try to build it; --asm moves it to the
                              asm-capable block
  * scripts/precomp/*.sage,*.py  two small, backward-compatible patches

All generated code lives in Jinja2 templates under add_parameter_set_templates/;
this file only holds the logic (prime math, modarith driver, file plumbing).

The reference field code is prime-agnostic: it only requires p prime and
p == 3 (mod 4) (which SQIsign needs anyway — it makes modpro == a^((p-3)/4),
i.e. exactly fp_exp3div4). With --asm, primes of the form c*2^t-1 with at
least 4 spare top-limb bits additionally get generated x86-64 and AArch64
assembly plus the sat64 binding (scripts/gen_fp/), and the set is
registered for both asm builds (they share one SVARIANT_S gate, so a set
always gets both or neither).

Example (the Mersenne prime 2^607-1):

    scripts/add_parameter_set.py p607_1 0x7f...f       # hex, or:
    scripts/add_parameter_set.py p607_1 '2**607-1' --lvl 1 --security 128

Then:

    cmake -B build -DSQISIGN_BUILD_TYPE=ref
    cmake --build build --target precomp_p607_1        # needs SageMath
    cmake --build build
    ctest --test-dir build -R p607_1
"""

import argparse
import glob
import os
import re
import shutil
import subprocess
import sys
import tempfile

try:
    import jinja2
except ImportError:
    sys.exit("error: this script needs Jinja2 (pip install jinja2)")

try:
    from sympy import isprime  # optional early sanity check
except ImportError:
    isprime = None

# --------------------------------------------------------------------------- #
# Locations / template engine
# --------------------------------------------------------------------------- #

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)                       # repo root
SRC = os.path.join(ROOT, "src")
TEMPLATES_DIR = os.path.join(SCRIPT_DIR, "add_parameter_set_templates")

_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(TEMPLATES_DIR),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
    undefined=jinja2.StrictUndefined,
)
_env.filters["hexlimb"] = lambda v: "0x%x" % v


def render(template, **ctx):
    return _env.get_template(template).render(**ctx)


# Modules that carry one subfolder per parameter set and just `include` the
# shared level-independent ("lvlx") CMake.  gf and precomp are handled
# specially below.  Value = does the module also have per-level test/ dirs.
STUB_MODULES = {
    "ec": True,
    "hd": False,
    "id2iso": True,
    "signature": True,
    "verification": False,
    "mp": True,
    "quaternion": True,
}

# The five generated C files the precomp library lists as sources.  They must
# exist on disk for cmake to configure; `make precomp_<name>` overwrites them.
PRECOMP_STUB_SOURCES = [
    "ec_params.c",
    "e0_basis.c",
    "torsion_constants.c",
    "quaternion_data.c",
    "endomorphism_action.c",
]

MARK_BEGIN = "# >>> ref-only parameter sets (managed by add_parameter_set.py) >>>"
MARK_END = "# <<< ref-only parameter sets <<<"
MARK_ASM_BEGIN = "# >>> asm-capable parameter sets (managed by add_parameter_set.py) >>>"
MARK_ASM_END = "# <<< asm-capable parameter sets <<<"
COND_REF = 'SQISIGN_BUILD_TYPE STREQUAL "ref" OR SQISIGN_BUILD_TYPE STREQUAL "opt"'
COND_ASM = (COND_REF + ' OR SQISIGN_BUILD_TYPE STREQUAL "broadwell"'
            ' OR SQISIGN_BUILD_TYPE STREQUAL "arm64"')


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #

class Ctx:
    def __init__(self, dry_run, force):
        self.dry_run = dry_run
        self.force = force

    def write(self, path, content):
        rel = os.path.relpath(path, ROOT)
        exists = os.path.exists(path)
        if exists and not self.force:
            print(f"  skip  {rel}  (exists; use --force to overwrite)")
            return
        verb = "over" if exists else "write"
        print(f"  {verb:5} {rel}")
        if self.dry_run:
            return
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)

    def render(self, path, template, **kw):
        self.write(path, render(template, **kw))

    def mkdir(self, path):
        print(f"  mkdir {os.path.relpath(path, ROOT)}/")
        if not self.dry_run:
            os.makedirs(path, exist_ok=True)

    def copy(self, src, dst):
        rel = os.path.relpath(dst, ROOT)
        if os.path.exists(dst) and not self.force:
            print(f"  skip  {rel}  (exists)")
            return
        print(f"  copy  {rel}")
        if self.dry_run:
            return
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)

    def patch(self, path, new_content, label):
        rel = os.path.relpath(path, ROOT)
        with open(path) as f:
            old = f.read()
        if old == new_content:
            print(f"  ok    {rel}  ({label}: already applied)")
            return
        print(f"  patch {rel}  ({label})")
        if self.dry_run:
            return
        with open(path, "w") as f:
            f.write(new_content)


def die(msg):
    sys.exit(f"error: {msg}")


# --------------------------------------------------------------------------- #
# modarith (monty.py) driver + Montgomery-constant math
# --------------------------------------------------------------------------- #

def find_monty(explicit):
    # Never guess a location: require --modarith or $MODARITH_DIR.
    for cand in filter(None, [explicit, os.environ.get("MODARITH_DIR")]):
        monty = os.path.join(cand, "monty.py") if os.path.isdir(cand) else cand
        if os.path.isfile(monty):
            return monty
    return None


def run_monty(monty, wordlen, prime_hex):
    """Run monty.py in a temp dir; return (field_c_text, base, N, nbytes)."""
    with tempfile.TemporaryDirectory() as tmp:
        # monty.py writes the C code to field.c in its CWD and self-tests it.
        proc = subprocess.run([sys.executable, monty, str(wordlen), prime_hex],
                              cwd=tmp, capture_output=True, text=True)
        field_c = os.path.join(tmp, "field.c")
        if not os.path.isfile(field_c):
            die(f"monty.py {wordlen} did not produce field.c\n"
                f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}")
        text = open(field_c).read()
    base = int(re.search(r"#define Radix\s+(\d+)", text).group(1))
    n = int(re.search(r"#define Nlimbs\s+(\d+)", text).group(1))
    nbytes = int(re.search(r"#define Nbytes\s+(\d+)", text).group(1))
    return text, base, n, nbytes


def mont_limbs(value, p, base, N):
    """Montgomery-nres(value) packed into N limbs of `base` bits each."""
    R = pow(2, N * base, p)
    v = (value * R) % p
    mask = (1 << base) - 1
    return [(v >> (base * i)) & mask for i in range(N)]


def make_field_file(monty_text, p, base, N, nbytes):
    """Transform raw monty output + render the generic SQIsign fp_* API.

    `nbytes`   = modarith byte length ceil(logp/8): the meaningful bytes.
    """
    core = monty_text.lstrip("\n")
    # ISO-C / -Wpedantic compatibility: avoid a bare __uint128_t/__int128_t
    # #define, mirroring the hand-edit in the committed lvlN field files.
    core = core.replace(
        "#define udpint __uint128_t\n#define dpint __uint128_t",
        "// for ISO-C compatibility\n"
        "__extension__ typedef __uint128_t fp_u128_t;\n"
        "#define udpint fp_u128_t\n#define dpint fp_u128_t")
    # gcc's -Werror=old-style-declaration wants function specifiers before the
    # return type; modarith emits `static <type> inline foo(...)`.
    core = re.sub(r"\bstatic (\w+) inline (\w+)\(", r"static inline \1 \2(", core)
    return render("field.c.j2",
                  core=core.rstrip(), nlimbs=N, nbytes=nbytes,
                  zero=[0] * N,
                  one=mont_limbs(1, p, base, N),
                  two_inv=mont_limbs(pow(2, -1, p), p, base, N),
                  three_inv=mont_limbs(pow(3, -1, p), p, base, N))


# --------------------------------------------------------------------------- #
# Shared-file patches (idempotent, backward compatible)
# --------------------------------------------------------------------------- #

def patch_top_cmake(ctx, name, asm=False):
    """Register `name` in SVARIANT_S for ref/opt, or the asm-capable block."""
    path = os.path.join(ROOT, "CMakeLists.txt")
    with open(path) as f:
        text = f.read()

    def parse(begin, end):
        m = re.search(re.escape(begin) + r".*?" + re.escape(end), text, re.S)
        if not m:
            return None
        found = re.search(r'list\(APPEND SVARIANT_S ([^)]*)\)', m.group(0))
        return re.findall(r'"([^"]+)"', found.group(1)) if found else []

    def block(begin, end, cond, names):
        return render("svariant_block.cmake.j2",
                      begin=begin, end=end, cond=cond, names=names).rstrip("\n")

    ref_names = parse(MARK_BEGIN, MARK_END)
    asm_names = parse(MARK_ASM_BEGIN, MARK_ASM_END) or []
    if ref_names is None:
        die("could not find the managed SVARIANT_S block in top CMakeLists.txt")
    tgt, other = (asm_names, ref_names) if asm else (ref_names, asm_names)
    if name not in tgt:
        tgt.append(name)
    if name in other:
        other.remove(name)

    new_text = re.sub(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                      lambda _: block(MARK_BEGIN, MARK_END, COND_REF, ref_names),
                      text, flags=re.S)
    asm_block = block(MARK_ASM_BEGIN, MARK_ASM_END, COND_ASM, asm_names)
    if MARK_ASM_BEGIN in new_text:
        new_text = re.sub(re.escape(MARK_ASM_BEGIN) + r".*?" + re.escape(MARK_ASM_END),
                          lambda _: asm_block, new_text, flags=re.S)
    else:
        new_text = new_text.replace(MARK_END, MARK_END + "\n" + asm_block, 1)

    ctx.patch(path, new_text, "SVARIANT_S registration")


def patch_precompute_sizes(ctx):
    """Derive the variant folder from CWD instead of the numeric `lvl`,
    so non-lvlN names work. Backward compatible: for lvlN, basename == lvlN."""
    path = os.path.join(SCRIPT_DIR, "precomp", "precompute_sizes.sage")
    with open(path) as f:
        text = f.read()
    if "add_parameter_set: variant from cwd" not in text:
        text = text.replace("algname = f'SQIsign_lvl{lvl}'",
                            render("inject_precompute_sizes.py.j2").rstrip("\n"))
        text = text.replace("../../../nistapi/lvl{lvl}/api.h",
                            "../../../nistapi/{variant}/api.h")
    ctx.patch(path, text, "sizes: variant-from-cwd")


def patch_parameters_py(ctx):
    """Let sqisign_parameters.txt carry an explicit `security = <bits>` that
    overrides the derived value (peer request). Backward compatible."""
    path = os.path.join(SCRIPT_DIR, "precomp", "parameters.py")
    anchor = "globals()['security_bits'] = security_bits\n"
    with open(path) as f:
        text = f.read()
    if "add_parameter_set: explicit security override" not in text:
        if anchor not in text:
            die("parameters.py did not match the expected patch anchor")
        text = text.replace(
            anchor, anchor + render("inject_parameters.py.j2"), 1)
    ctx.patch(path, text, "parameters: security override")


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def parse_prime(s):
    try:
        return int(s, 16) if s.lower().startswith("0x") \
            else int(eval(s, {"__builtins__": {}}, {}))
    except Exception as e:
        die(f"could not parse prime {s!r}: {e}")


def main():
    ap = argparse.ArgumentParser(description="Scaffold a new SQIsign parameter set.")
    ap.add_argument("name", help="variant name, e.g. p607_1 (folder name across modules)")
    ap.add_argument("prime", help="prime p as 0x-hex or a python expr like '2**607-1'")
    ap.add_argument("--lvl", type=int, default=1, help="numeric NIST level label (default 1)")
    ap.add_argument("--security", type=int, default=None,
                    help="explicit security bits written to parameters.txt")
    ap.add_argument("--tag", default=None,
                    help="field-file tag (default: the variant name) -> fp_<tag>_<radix>.c")
    ap.add_argument("--modarith", default=None,
                    help="path to modarith dir or monty.py (required unless $MODARITH_DIR is set)")
    ap.add_argument("--asm", action="store_true",
                    help="also generate the broadwell + arm64 asm and the sat64 "
                         "binding, and register the set for the asm builds "
                         "(needs p = c*2^t-1 with >= 4 spare top-limb bits)")
    ap.add_argument("--no-gen-field", action="store_true",
                    help="do not run modarith; leave field files to be dropped in by hand")
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--dry-run", action="store_true", help="print actions, write nothing")
    ap.add_argument("--skip-next-steps", action="store_true",
                    help="only print the build/precomp/KAT steps instead of running them")
    args = ap.parse_args()

    name = args.name
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", name):
        die(f"invalid variant name {name!r} (use letters/digits/underscore)")
    tag = args.tag or name

    p = parse_prime(args.prime)
    if p < (1 << 100):
        die("prime looks too small for a real parameter set")
    if isprime is None:
        print("note: sympy not installed; skipping the primality check "
              "(monty.py and precomp still reject non-primes)")
    elif not isprime(p):
        die("p is not prime")
    if p % 4 != 3:
        die("p must be 3 (mod 4) for the reference field code (SQIsign requires this)")
    logp = p.bit_length()
    prime_hex = "0x%x" % p
    print(f"parameter set '{name}': p = 2^{logp-1}..; {logp} bits; p mod 4 = 3  OK")

    ctx = Ctx(args.dry_run, args.force)

    # --- field arithmetic via modarith ------------------------------------- #
    field64 = field32 = None
    if not args.no_gen_field:
        monty = find_monty(args.modarith)
        if not monty:
            die("modarith monty.py not found; pass --modarith PATH, set "
                "$MODARITH_DIR, or use --no-gen-field")
        print(f"generating reference field code with {monty}")
        t64, base64, nlimbs64, nbytes = run_monty(monty, 64, prime_hex)
        field64 = make_field_file(t64, p, base64, nlimbs64, nbytes)
        t32, base32, nlimbs32, nbytes32 = run_monty(monty, 32, prime_hex)
        field32 = make_field_file(t32, p, base32, nlimbs32, nbytes32)
        print(f"  radix 64: {nlimbs64} limbs, radix {base64}; "
              f"radix 32: {nlimbs32} limbs, radix {base32}; {nbytes} bytes")

    print("\nscaffolding files:")

    # --- precomp/ref/<name>/ ------------------------------------------------ #
    pc = os.path.join(SRC, "precomp", "ref", name)
    ctx.render(os.path.join(pc, "sqisign_parameters.txt"),
               "sqisign_parameters.txt.j2",
               lvl=args.lvl, prime_hex=prime_hex, security=args.security)
    ctx.render(os.path.join(pc, "CMakeLists.txt"), "lvlx_include.cmake.j2")
    # `make precomp_<name>` writes fp_constants.h (+ the other headers) here.
    ctx.mkdir(os.path.join(pc, "include"))
    for src in PRECOMP_STUB_SOURCES:
        ctx.render(os.path.join(pc, src), "precomp_stub.c.j2", name=name)

    # --- gf/ref/<name>/ ----------------------------------------------------- #
    gf = os.path.join(SRC, "gf", "ref", name)
    ctx.render(os.path.join(gf, "CMakeLists.txt"), "gf_CMakeLists.txt.j2", tag=tag)
    ctx.render(os.path.join(gf, "test", "CMakeLists.txt"), "lvlx_test_include.cmake.j2")
    ctx.render(os.path.join(gf, f"fp_{tag}.c"), "gf_fp_glue.c.j2", tag=tag)
    if field64 is not None:
        ctx.write(os.path.join(gf, f"fp_{tag}_64.inc"), field64)
        ctx.write(os.path.join(gf, f"fp_{tag}_32.inc"), field32)
    else:
        print(f"  NOTE  drop fp_{tag}_64.inc and fp_{tag}_32.inc into "
              f"{os.path.relpath(gf, ROOT)}/ by hand (--no-gen-field)")

    # --- nistapi/<name>/ ---------------------------------------------------- #
    try:
        ctx.copy(os.path.join(SRC, "nistapi", "api.c"),
                 os.path.join(SRC, "nistapi", name, "api.c"))
    except shutil.SameFileError:
        pass
    #      api.h is generated by precompute_sizes.sage during `make precomp`.

    # --- level-dependent module stubs -------------------------------------- #
    for mod, has_test in STUB_MODULES.items():
        base = os.path.join(SRC, mod, "ref", name)
        ctx.render(os.path.join(base, "CMakeLists.txt"), "lvlx_include.cmake.j2")
        if has_test:
            ctx.render(os.path.join(base, "test", "CMakeLists.txt"),
                       "lvlx_test_include.cmake.j2")

    # --- broadwell + arm64: asm + sat64 binding ------------------------------ #
    if args.asm:
        n = p + 1
        t_asm = (n & -n).bit_length() - 1
        c_asm = n >> t_asm
        bw_asm = os.path.join(SRC, "gf", "broadwell", name, "fp_asm.S")
        a64_asm = os.path.join(SRC, "gf", "arm64", name, "fp_asm.S")
        gen_dir = os.path.join(SCRIPT_DIR, "gen_fp")
        n_limbs = (p.bit_length() + 63) // 64
        spill = (["--spill-pointers-max"] if n_limbs > 10 else
                 ["--spill-pointers"] if n_limbs > 8 else [])
        cmds = [
            [sys.executable, os.path.join(gen_dir, "gen_fp_asm_broadwell.py"),
             "--c", str(c_asm), "--t", str(t_asm)] + spill + ["-o", bw_asm],
            [sys.executable, os.path.join(gen_dir, "gen_fp_asm_arm64.py"),
             "--c", str(c_asm), "--t", str(t_asm), "-o", a64_asm],
            [sys.executable, os.path.join(gen_dir, "gen_fp_c.py"),
             "--name", name, "--c", str(c_asm), "--t", str(t_asm)]
            + (["--force"] if args.force else []),
        ]
        print("\nbroadwell + arm64 field code:")
        for cmd in cmds:
            print("  run   " + " ".join(os.path.relpath(x, ROOT)
                                        if os.path.isabs(x) else x for x in cmd[1:]))
            if not args.dry_run:
                os.makedirs(os.path.dirname(bw_asm), exist_ok=True)
                os.makedirs(os.path.dirname(a64_asm), exist_ok=True)
                if subprocess.run(cmd).returncode != 0:
                    die("asm generation failed (the prime must be c*2^t-1 "
                        "with >= 4 spare bits in the top limb)")

    # --- shared-file patches ------------------------------------------------ #
    print("\npatching shared files:")
    patch_top_cmake(ctx, name, asm=args.asm)
    patch_precompute_sizes(ctx)
    patch_parameters_py(ctx)
    #      encoded_sizes.h and nistapi/<name>/api.h are generated by
    #      `make precomp_<name>` (precompute_sizes.sage), not here.

    steps = [
        (["cmake", "-B", "build", "-DSQISIGN_BUILD_TYPE=ref"], None),
        (["cmake", "--build", "build", "--target", f"precomp_{name}"], "SageMath: fills the stubs"),
        (["cmake", "-B", "build", "-DSQISIGN_BUILD_TYPE=ref"], "re-configure (new headers)"),
        (["cmake", "--build", "build"], None),
        (["cmake", "--build", "build", "--target",
          f"sqisign_test_gf_{name}_fp", f"sqisign_test_gf_{name}_fp2"],
         "validate the generated field arithmetic in isolation"),
        (["cmake", "--build", "build", "--target", f"PQCgenKAT_sign_{name}"], "Known-Answer Tests"),
        ([f"./PQCgenKAT_sign_{name}"], "run in build/apps"),
    ]
    ctest = (["ctest", "--test-dir", "build", "-R", name], "needs KAT/ populated first")

    if args.skip_next_steps or args.dry_run:
        print("\ndone. next steps:\n")
        for cmd, note in steps + [ctest]:
            if cmd is ctest[0]:
                print(f"\n  cp build/apps/PQCsignKAT_*_SQIsign_{name}.req "
                      f"build/apps/PQCsignKAT_*_SQIsign_{name}.rsp KAT/")
            print(f"  {' '.join(cmd):<66} {'# ' + note if note else ''}".rstrip())
        if args.asm:
            print("\n  # on an x86-64 host:")
            print("  cmake -B build_bw -DSQISIGN_BUILD_TYPE=broadwell")
            print("  cmake --build build_bw")
            print(f"  ctest --test-dir build_bw -R {name}")
            print("\n  # on an AArch64 host:")
            print("  cmake -B build_arm64 -DSQISIGN_BUILD_TYPE=arm64")
            print("  cmake --build build_arm64")
            print(f"  ctest --test-dir build_arm64 -R {name}")
        return

    def run(cmd, note=None):
        cwd = os.path.join(ROOT, "build", "apps") if cmd[0].startswith("./") else ROOT
        print(f"\n$ {' '.join(cmd)}" + (f"   # {note}" if note else ""))
        if subprocess.run(cmd, cwd=cwd).returncode != 0:
            die(f"failed: {' '.join(cmd)}")

    print("\ndone. running next steps:")
    for cmd, note in steps:
        run(cmd, note)

    kats = glob.glob(os.path.join(ROOT, "build", "apps", f"PQCsignKAT_*_SQIsign_{name}.*"))
    for k in kats:
        ctx.copy(k, os.path.join(ROOT, "KAT", os.path.basename(k)))
    print(f"\n{len(kats)} KAT file(s) copied to KAT/")
    run(*ctest)
    print("\nall steps passed")
    if args.asm:
        print("\nverify the broadwell build on an x86-64 host:")
        print("  cmake -B build_bw -DSQISIGN_BUILD_TYPE=broadwell")
        print(f"  cmake --build build_bw && ctest --test-dir build_bw -R {name}")
        print("verify the arm64 build on an AArch64 host:")
        print("  cmake -B build_arm64 -DSQISIGN_BUILD_TYPE=arm64")
        print(f"  cmake --build build_arm64 && ctest --test-dir build_arm64 -R {name}")


if __name__ == "__main__":
    main()
