# SPDX-License-Identifier: Apache-2.0
#
# The code the quality checks leave alone. Sourced by scripts/cppcheck.sh, scripts/clang-tidy.sh and
# scripts/coverage.sh; not executable on its own.
#
#   QC_EXCLUDE          generated and vendored code: not ours, so we neither reformat it nor report defects in it
#   QC_EXCLUDE_HARNESS  test and bench scaffolding: analyzed like the rest, but measures nothing about the library, so
#                       coverage leaves it out
#
# Entries are repository-relative paths, files or directories, with no wildcards: a leading wildcard silently matches
# nothing. Consumers normalize them: cppcheck.sh passes relative and absolute spellings, since the path style in
# compile_commands.json depends on the CMake version, and routes headers through --suppress, which -i ignores.
# qc_exclude_check rejects an entry that no longer exists; qc_exclude_regexes converts the lists to the anchored regexes
# clang-tidy and gcovr take instead of paths.

QC_EXCLUDE=(
    # --- generated ---------------------------------------------------------------------------------------------
    src/precomp                              # SageMath-generated constants (scripts/precomp/*.sage)
    src/gf/ref/p324_3                        # modarith-generated: fp_p324_3_{32,64}.c
    src/gf/ref/p500_27                       # modarith-generated: fp_p500_27_{32,64}.c
    src/gf/ref/p664_17                       # modarith-generated: fp_p664_17_{32,64}.c
    include/sqisign_namespace.h              # generated by scripts/check_namespace.sh

    # --- vendored ----------------------------------------------------------------------------------------------
    src/common/ref/aes_c.c                   # PQClean, in turn BearSSL
    src/common/ref/include/aes.h             # ditto
    src/common/ref/randombytes_ctrdrbg.c     # NIST rng.c derivative
    src/common/generic/fips202.c             # PQClean, in turn supercop
    src/common/generic/include/fips202.h     # ditto
    src/common/generic/randombytes_system.c  # randombytes library
    src/common/generic/include/bench_macos.h # third-party macOS cycle-counter shim
    apps/PQCgenKAT_sign.c                    # NIST-supplied KAT harness
    apps/PQCgenKAT_sign_pqm4.c               # ditto
    test/test_kat.c                          # ditto
)

QC_EXCLUDE_HARNESS=(
    src/common/generic/include/bench.h
    src/common/generic/include/bench_test_arguments.h
    apps/benchmark.c                         # never run by ctest
    apps/fuzz_sign.c                         # ditto
    apps/fuzz_verify.c                       # ditto
)

# An exclusion that has stopped matching looks exactly like a clean run, so a stale entry is fatal.
qc_exclude_check() {
    local qc_path qc_status=0
    for qc_path in "$@"; do
        [ -e "$qc_path" ] || {
            echo "error: the exclusion list in ${BASH_SOURCE[0]} names '$qc_path', which does not exist" >&2
            qc_status=1
        }
    done
    return "$qc_status"
}

# One regex per argument, anchored at the start of a repository-relative path. Directories get a trailing slash to avoid
# an undesired prefix match.
qc_exclude_regexes() {
    local qc_path qc_re
    for qc_path in "$@"; do
        qc_re=$(printf '%s' "$qc_path" | sed 's/[][\\.^$|?*+(){}]/\\&/g')
        [ -d "$qc_path" ] && qc_re="$qc_re/"
        printf '%s\n' "$qc_re"
    done
}
